### ISSUE TITLE
[bug] Edit project: view focus

### ISSUE THREAD

**Issue by princemaple** [randy3k/Project-Manager#14]
Hi @randy3k , awesome plugin!

When trying to navigate to the `.sublime-project` file using `Project Manager -> Edit Project`
the `.sublime-project` is opened without focused.

I tried calling `focus_view` with the view returned by `window.open_file` in `edit_project` but seems to have no effect.

I'm on latest ST3 and OSX yosemite.

**Comment by NetiTrinR** [comment]
I am still having the issue. Is there any way to check to see if the fix has been pulled in? Package Control says that there isn't any available upgrades for any packages.

**Comment by randy3k** [comment]
May be, your problem is related to #2? If that is the case, I am sorry to tell you that it is still not fixed yet.
