### ISSUE TITLE
Support nested projects

### ISSUE THREAD

**Issue by Dremora** [randy3k/Project-Manager#18]
In Atom, I can give my projects names like: `superproject/my-project`. Trying to do the same in this plugin does result in a folder `superproject` being created under `Packages/User/Projects`. However, the plugin doesn't seem to be able to read nested folders and doesn't list newly created package.

**Comment by scottstensland** [comment]
I second this notion - sublime text 3 really needs ability to bundle multiple projects so as a set they can be opened and closed  ...  retaining current behaviour where each project has its own window

**Comment by randy3k** [comment]
let me think about this. in current implementation, subfolder under `Packages/User/Projects` actually are machine specific folder. For example, `Packages/User/Projects/ComputerA` will be only read by `ComputerA`.

**Comment by randy3k** [comment]
nested projects are now supported 8c6b352dcf1b582ead02a9f7eb0f404b5d628650

**Comment by randy3k** [comment]
@scottstensland there are some difficulties in opening and closing the projects simultaneously.
