### ISSUE TITLE
ST3 loses focus on project change

### ISSUE THREAD

**Issue by highend** [randy3k/Project-Manager#2]
Hi Randy,

latest revision (Project-Manager), ST3 Build 3064 x86

Whenever I switch from one project to a different one (which works fine) the ST3 window loses it's focus.

Windows Server 2012 R2...

**Comment by LoneBoco** [comment]
This issue has been bugging me for some time now, so I decided to experiment a bit.  I don't know if any of this will be helpful in identifying the issue, but it doesn't hurt.

When Sublime Text 3 is running, the cursor blinks.  CTRL+ALT+P opens Project Manager.  Project/Quick Switch Project opens the old quick switch window.

I use Project Manager to switch projects and my window loses focus.  No key combination will return the focus.  ALT+Space doesn't show anything.  I didn't even see anything on Process Explorer.  However, when I press ALT+F4, interesting things happen.

First, my Sublime Text 3 window gains focus.  Something was holding focus and I had managed to kill whatever it was.  My text cursor does not blink anymore.  CTRL+ALT+P doesn't open the Project Manager window anymore (neither does Project/Project Manager).  Project/Quick Switch Project opens the old quick switch menu AND the new Project Manager window.

I'm not quite sure how to figure out what I had closed with ALT+F4.  This makes it seem like a bug with Sublime Text itself.

I am using Sublime Text 3 dev build 3085 at the time of this writing on Windows 7.

**Comment by randy3k** [comment]
@LoneBoco, thanks for the report. It is so weird that I have never faced this issue, though I am running the windows on virtual machine..

I have really no idea what is going on there, I guess that it is a bug of Sublime Text itself. And it is not sure whether it is a problem only related to Windows 7 users, as all reports here are for Windows 7.

**Comment by usernamelectro** [comment]
This is also happening in my Windows 8.1. It is annoying from time to time.

**Comment by randy3k** [comment]
The way that `Simple Project manager` works is very different to `Project manager `. `Project manager` requires opening the project file `sublime-project`, and I think it is the part that ST3 contains a bug. Of course, it is only my guess...

**Comment by LoneBoco** [comment]
I just tested it out with a program called Windows Focus Logger.  When the bug happens, it shows that an offscreen window owned by sublime_text.exe has stolen focus.  Unfortunately it doesn't give much more info than that.  It might be prudent to open a bug with Sublime Text itself about the issue.

**Comment by timpauvictor** [comment]
I'm still encountering this issue

**Comment by Samjin** [comment]
Having the same issue on all my 3 laptops. Window7, sublime3.

**Comment by randy3k** [comment]
Odd enough, I can reproduce it now on my machine. Trying to fix it, but no luck so .

**Comment by randy3k** [comment]
I believe that 4335251076f3d8dd7028439a3eb9909ea2538918 fixes this long standing bug.

**Comment by old9** [comment]
Still loses focus when choosing **Open Project in New Window**.
The focus is neither on the newly opened window or the old one, only after pressing Alt+F4 does it bring the focus back to the newly opened window from some mysterious thing.

version 0.7.11
ST3 build 3144
Windows 10 64bit 1607

**Comment by randy3k** [comment]
@old9 
I have just tagged a new release 0.7.12, should be fixed now.
