### ISSUE TITLE
OS X project change triggers exit from fullscreen mode

### ISSUE THREAD

**Issue by max-mykhailenko** [randy3k/Project-Manager#21]
ST 3 v.3075
OSX latest

**Comment by randy3k** [comment]
weird, i cannot reproduce it on ST 3 3065, yosemite.

**Comment by randy3k** [comment]
Could you describe how to reproduce this?

**Comment by max-mykhailenko** [comment]
You can reproduce that in several steps:
- open project
- turn on fullscreen mode (ctrl+cmd+F)
- switch project

Seems that plugin at first closes window and opens new with selected project.

**Comment by randy3k** [comment]
I still cannot reproduce it. Check this video: https://www.youtube.com/watch?v=vWke5MFCwVU

**Comment by max-mykhailenko** [comment]
http://quick.as/v64mfdoqv

**Comment by randy3k** [comment]
what if you don't do full screen? will the project open in the same window?

**Comment by max-mykhailenko** [comment]
Seems, that window closes and then opens new one.

**Comment by randy3k** [comment]
does the window close, or just the side bar close as in my video?

**Comment by max-mykhailenko** [comment]
http://quick.as/7bnzsgomz

**Comment by randy3k** [comment]
I can only conclude that it is due to a change in the API. Could you downgrade and give 3065 a try?

**Comment by randy3k** [comment]
I hv figured it out, newer version of sublime text has an option available for OS X which controls the behavior of an empty window. You can revert to the old behavior by configuring your user settings as

```
	"close_windows_when_empty": false,
```

**Comment by max-mykhailenko** [comment]
Thanks!

**Comment by randy3k** [comment]
I am now pushing an updated version which forces `close_windows_when_empty` to be `false` when switching projects. So that you don't have to specify `close_windows_when_empty` in your user settings file (which is less desirable).

**Comment by max-mykhailenko** [comment]
And after switch returns it to `true`?

**Comment by randy3k** [comment]
Return to its default value.
