### ISSUE TITLE
Use Local Project Dir not working on v0.5.4

### ISSUE THREAD

**Issue by JuanSanMedina** [randy3k/Project-Manager#22]
Even though I set my pm.sublime-settings: 

{
    "use_local_projects_dir": true,
}

The plugin does not use the local folder. 

Any ideas for this issue?

**Comment by randy3k** [comment]
sorry for the buy. fix now

**Comment by JuanSanMedina** [comment]
Hello @randy3k, still not working. 

In addition, if Projects/library.json is empty, project manager menu (^ + cmd + p) doesn't show up.

**Comment by randy3k** [comment]
@JuanSanMedina, sorry for the fix....it is fixed now and I double checked :)
