### ISSUE TITLE
ST3 switch project causes re-opening of a new window on a different screen

### ISSUE THREAD

**Issue by mkeeler** [randy3k/Project-Manager#24]
I have ST3 open on an external monitor. Up until build 3080 of ST3 switching projects would open the new project within the same window on my external monitor. As of build 3080 it now opens a new window on my other screen causing me to have to drag it back to the correct screen.

I am not sure if this is an issue with the plugin or with ST3 itself.

**Comment by randy3k** [comment]
The newer version must have changed somethin, related to #21.

**Comment by randy3k** [comment]
I hv figured it out, newer version of sublime text has an option available for OS X which controls the behavior of an empty window. You can revert to the old behavior by configuring your user settings as

```
	"close_windows_when_empty": false,
```

**Comment by randy3k** [comment]
I am now pushing an updated version which forces `close_windows_when_empty` to be `false` when switching projects. So that you don't have to specify `close_windows_when_empty` in your user settings file (which is less desirable).
