### ISSUE TITLE
Relative paths, symlinks and $HOME folder

### ISSUE THREAD

**Issue by margaritis** [randy3k/Project-Manager#26]
I have been trying to use a robust setup cause i am working on 4 differences devices. The issue here is that when enabling the projects_fpath in order to auto discover the sublime projects that have already been created, i can not reference in any way the $HOME directory where my .sublime-projects lie.

I have tried to use relative paths to climb up the ladder to $HOME but to no avail. 

My last attempt was to use symlinks of my .sublime-projects inside the /Users/Projects/ which did not work either.

![screen shot 2015-05-13 at 02 40 23](https://cloud.githubusercontent.com/assets/5788810/7601011/d6e68cd0-f919-11e4-804b-128ba2d88efb.png)

Is there any way to allow symlinks or to reference our $HOME without being specific so that can be used in other devices as well?

P.S. I came along the following code which returns the $HOME folder. Could this be somehow integrated to Project Manager so that we can use it? Is it possible to make a fix so the plugin follows symlinks?

```
from os.path import expanduser
home = expanduser("~")
```

**Comment by randy3k** [comment]
Did you try the `use_local_projects_dir` option in the settings? It should somehow resolve part of your concerns.

**Comment by randy3k** [comment]
Now `~` is expanded. e64cfedd804f18a35c15af73a17b83ccf0241944

**Comment by margaritis** [comment]
Superb @randy3k! It works flawlessly! :+1:

**Comment by randy3k** [comment]
Project Manager is now also following symlinks. 4520381

**Comment by randy3k** [comment]
Can it be closed now?

**Comment by margaritis** [comment]
Go ahead @randy3k. Thanks for the symlinks!

**Comment by randy3k** [comment]
No problem.
