### ISSUE TITLE
New project creation forces requirement of added / tracked folder (req. headless projects)

### ISSUE THREAD

**Issue by KangarooCreativeTeam** [randy3k/Project-Manager#27]
Hiya, I want to be able to add projects that have no folder on disk associated with them.  
This could be because I haven't created the folders just yet, or because I want a 'headless' workspace that allows me to write / paste stuff & have it managed by Project Manager (close without saving to file & tabs will still reopen keeping state; one of the best things about of ST projects!)

Usage: (issue)
When I want to add a new project to Project Manager and *don't* have a folder added (to sidebar), it won't work (nothing happens at all when selecting 'Add Project'). 

Usage: (my workaround)
If I first add _any_ random folder to ST (drag & drop), it then works as expected & allows me to create a project.  *Then* I can remove that folder from the project, & Project Manager continues to work perfectly, except without any folder (as desired). 

Solution:
Project Manager shouldn't need / require any folder added to project when creating a project

I'm using ST3 Build 3083 on Arch Linux x64

(Also; as I've said before - I really like this package & appreciate the good work you've put into it! - Thank you!)

O_O

--HEAD KANGAROO

**Comment by randy3k** [comment]
Done.

**Comment by KangarooCreativeTeam** [comment]
Awesome!  :)

Thank you

^_^

**Comment by KangarooCreativeTeam** [comment]
Update - this doesn't work correctly if using the setting: ```"close_windows_when_empty": true,``` (e.g. in user preferences file);

After naming the new project, it opens a new window with the project loaded with zero content / no tabs (in an empty state)

This causes the _close_windows_when_empty_ to trigger, immediately closing the window. 

Loading the project does the same thing, immediately closing the empty window.  (No time to type any content to make it not-empty)

However, like before, if any folder is added to the window, & a project is created, it opens a new window with empty content, but because it also has the folder loaded in the sidebar, it does not trigger the _close_windows_when_empty_.

So; is this an issue with ST core? 

Is it possible to carry the current tabs of the open window over to the new project when created? 

O_O

--HEAD KANGAROO

**Comment by randy3k** [comment]
It is annoying...
It is an issue of ST. It fails to open an empty project and close the project immediately. One possible to solution is to set `close_windows_when_empty` to `false` temperately for empty projects.

**Comment by KangarooCreativeTeam** [comment]
Okay - don't worry about it.  It's clearly an issue upstream in ST's core. 

I still think it's an improvement with what you've implemented so far for this issue (folder-less new project support).

Thank you  ^_^

^_^

--HEAD KANGAROO

**Comment by randy3k** [comment]
Check out the latest version. It should do the jobs.

**Comment by randy3k** [comment]
Oh, there is a slight problem...fixing it.
