### ISSUE TITLE
Slow and laggy switching projects

### ISSUE THREAD

**Issue by jlem** [randy3k/Project-Manager#28]
The default sublime text project switcher is lightning fast, making it very easy to jump in and out of projects to look something up or to see how you did something. Project-Manager slowly closes the current project, and slowly opens the new project, making switching much less snappy and efficient.

**Comment by randy3k** [comment]
Project Manager uses dirty tricks to close and open projects. There is no way to improve it unless Sublime Text api provides a proper way to open and close projects.

**Comment by randy3k** [comment]
It turns out I manage to speed up the time between switching projects b57744c8586211215ff43702a263d41e1bcfd601. Yeah :)

**Comment by webcaetano** [comment]
same here.
@randy3k  make a PR from it.
