### ISSUE TITLE
Project quick switch list is not as useful as ST3's default list

### ISSUE THREAD

**Issue by jlem** [randy3k/Project-Manager#29]
ST3's default project switcher will intelligent order projects by recency, and will allow you to do quick toggling by automatically highlighting the last project you had open, and putting it at the top.

So if you last used Project B, and you are on Project A, you could just super+ctrl+p+enter to instantly switch to Project B, and then because you were last on Project A when you switched to Project B, Project A will be on top and highlighted for you and you can do the same thing to keep toggling and jumping back and forth between those projects.

Also, the project manager options should not be in the list of project switching - that is what the command pallet is for. The project quick switch list should just be projects, and nothing more.

That said, I love how you can define a project patch for sublime to look in, and I love how it strips out the silly .sublime-project extension from the names, so that part is awesome.

**Comment by randy3k** [comment]
It totally makes sense and I will consider it.

**Comment by pelletiermaxime** [comment]
I really like this package, but my first tought after using it for a few seconds was exactly the same. I switch projects all the time during my day, so I would really like the quick project switch behavior to be more like it is in default subl. Thanks !

**Comment by randy3k** [comment]
In the most recent commit f3ed7ce, you can specify `"show_recent_projects_first" : true` in the settings to show recent projects first. I hope it will provoide more similar experience to the default sublime behavior.

I will publish it to package control a few day later.
