### ISSUE TITLE
Feature to remove project ?

### ISSUE THREAD

**Issue by ptcong** [randy3k/Project-Manager#30]
@randy3k , thanks for your amazing package!.
But what you think about feature remove project ? 
Because sometimes people want to remove a project, currently they must go to project folder and remove project files. 
It will be better if have the feature.

**Comment by randy3k** [comment]
There is a remove project option.

**Comment by ptcong** [comment]
Sorry, but when i open a project, and type Cmd + Ctrl + P, i no see remove project option, even with ST's Project menu.
I mean remove **.sublime-project** and **.sublime-workspace** file of a project. Not remove folders in a projects.
