### ISSUE TITLE
Can't understand how to use

### ISSUE THREAD

**Issue by sporto** [randy3k/Project-Manager#35]
I'm trying to follow the instructions, I don't know if it is just not working or I'm missing something:

- Open sublime with a folder
- Use 'Add Project' from Project manager
- Then when I open project manager again it doesn't show me anything new, just: Project Manager (More options), Add Project and Import.sublime-project

I open `library.json` to see what is in there and is just empty. So it seems that 'Add Project' doesn't do anything.

What I'm missing here? Thanks

**Comment by sporto** [comment]
Ok, dismiss all this, I had a theme that was totally obscuring the input field on the bottom of sublime

**Comment by randy3k** [comment]
Great.
