### ISSUE TITLE
Opening project closes current project

### ISSUE THREAD

**Issue by andersennl** [randy3k/Project-Manager#36]
I've been using (enjoying) this package for a little while now and until now, when I opened a project from the projects overview (from this package), a new window opened with the selected project and I could then quickly switch between these sublime windows. 

I'm not sure if there was an update for this package or what caused this but this behavior has suddenly changed. Whenever I now open a project from the project overview, the current window is like being closed and the other project's window opened.

This is really annoying as I can't quick switch between projects anymore (using cmd + < on german keyboard layout) and have to reopen everything again and again, which takes longer. Maybe I should mention that I'm working with microservices which requires switching between projects a lot.

Is there some (new) setting to get back the old behavior? Thanks!

**Comment by randy3k** [comment]
I believe what you have encountered are the old behavior and the default behavior. If you want to open the project in a new window, there is a "Open Project in New Window" option.
