### ISSUE TITLE
Shortcut to open panel not working after last update

### ISSUE THREAD

**Issue by paip** [randy3k/Project-Manager#41]
After the last update on OSX, the shortcut to open the panel isn't working any more, it opens the default project switcher. I tried reapplying the shortcut manually on the Sublime user keymap file, but with no luck.

**Comment by randy3k** [comment]
Please note that the layout of Project Manager has been changed. If you are seeing a different layout, it might be the reason.

If it is no the case, I suggest you re-installing Project Manager. The projects' files are stored in a separate location and they would be deleted when PM is uninstalled.

**Comment by jerome-toole** [comment]
I've also got this issue. I've just installed Project Manager for the first time.

As soon as Project Manager is installed, my `CTRL+CMD+P` shortcut does nothing. 
As soon as I remove the package it shows again.

**Comment by randy3k** [comment]
Did you add any project items to Project Manager?

**Comment by mikegazdag** [comment]
Thanks @randy3k, after adding a project, the shortcut worked. Maybe we should update the docs to mention that the keyboard shortcut won't work without a project.

**Comment by randy3k** [comment]
@mikegazdag 493fa2d8ba140dc97e6406b5d8a4f9268f909c1a should address the issue.

**Comment by jerome-toole** [comment]
I hadn't understood that Project Manager wouldn't manage existing projects. 

Maybe this could be made more clear as a sort of 'Getting Started' section.
