### ISSUE TITLE
can' find it by package control

### ISSUE THREAD

**Issue by iulo** [randy3k/Project-Manager#42]

**Comment by randy3k** [comment]
Are you using sublime text 3? Project manager is only available on ST3.

**Comment by iulo** [comment]
yes I am

**Comment by iulo** [comment]
[picture here](http://7xpdjc.com1.z0.glb.clouddn.com/project%20manager.png)

**Comment by randy3k** [comment]
It is called **Project** Manager.

**Comment by iulo** [comment]
Ops!~ sorry for that. It work with my macbook now, tomorrow I will try with my windows machine. sorry for that agian

**Comment by iulo** [comment]
[picture here](http://7xpdjc.com1.z0.glb.clouddn.com/projectmanage.png)     
[picture here](http://7xpdjc.com1.z0.glb.clouddn.com/projectmanager.png)     

also don't

**Comment by randy3k** [comment]
Have you already installed Project Manager? Can you check "Package Control: List Packages"

**Comment by iulo** [comment]
No, but it could be found with package control today, weird. 
Tks anyway
