### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by joneschrisan** [randy3k/Project-Manager#45]
A simple sentence "You can install Project Manager via Package Control." is not enough on how to install.

**Comment by randy3k** [comment]
A little Google search should lead you to https://packagecontrol.io

**Comment by joneschrisan** [comment]
Not the point. Install instructions should explain how to install not just say it is installable.

**Comment by randy3k** [comment]
Well,...I may wrongly assume that Package Control is installed for all Sublime Text users.
