### ISSUE TITLE
Error On Project Rename

### ISSUE THREAD

**Issue by Enteleform** [randy3k/Project-Manager#47]
I'm getting the following error if I rename a project that is currently open, close ST, and reopen ST:

![screenshot_032316_120137_am](https://cloud.githubusercontent.com/assets/10906415/13975372/e81a5a7c-f08a-11e5-902a-8db80ce72f23.jpg)

It seems there is some sort of issue with how your plugin is reloading the active project after it is renamed. &nbsp; However, after renaming the project, the sidebar maintains its settings until ST is closed.

After the error, the project can easily be restored by using the `Project Manager: Open Project` command.

&nbsp;
&nbsp;

**System Info:**
*ST3, Stable Channel Build 3103
Windows 10 Pro, Build 10586*

**Comment by randy3k** [comment]
I am trying to make sense of it, is MyProject the original name or the updated project name?

I am not sure why you have "[ Project ]" in the middle of the file path. Did you change the `projects_dir` setting?

**Comment by Enteleform** [comment]
`MyProject` is the original name.

My custom `projects_dir` setting is:
`"C:/Users/Fico/AppData/Roaming/Sublime Text 3/Packages/[ Projects ]/"`

The custom directory seems like it works fine, all of my projects are populated into the QuickPanel for the `Project Manager: Open Project` command.

**Comment by randy3k** [comment]
Er...I will look into it tomorrow. It's bed time here. :smile:

**Comment by Enteleform** [comment]
Also, I just noticed that after changing the project name - the project name in the title-bar reflects that the original project is still open.

**Comment by randy3k** [comment]
I think I understand what caused the problem, and it seems that it only happens on Windows (that's why I didn't notice it.) I will fix it later today/ this week since it is not very urgent.

**Comment by randy3k** [comment]
Could you try 0.6.7 and see if it fixes it?

**Comment by Enteleform** [comment]
Just tried it, same issue.

**Comment by randy3k** [comment]
One more time to try: if you run the following code in Sublime console, the project should be closed (may need to rename "MyProject"). And then open ST again to see if you will see the same error.

```python
import sys; sys.modules['Project Manager'].pm.Manager(sublime.active_window()).close_project("MyProject")
```

**Comment by Enteleform** [comment]
I tried it, nothing happens - it just returns `False`

**Comment by randy3k** [comment]
Thank you for helping debugging.
Make sure that "MyProject" is opened and run the followings.

```python
import sys; sys.modules['Project Manager'].pm.Manager(window).project_file_name("MyProject")
```

```python
 window.project_file_name()
```

**Comment by Enteleform** [comment]
Resuts:

```
>>> import sys; sys.modules['Project Manager'].pm.Manager(window).project_file_name("MyProject")
'C:/Users/Fico/AppData/Roaming/Sublime Text 3/Packages/[ Projects ]/MyProject.sublime-project'

>>> window.project_file_name()
'C:\\Users\\Fico\\AppData\\Roaming\\Sublime Text 3\\Packages\\[ Projects ]\\MyProject.sublime-project'
```

**Comment by randy3k** [comment]
It is odd, my windows always shows `\\`. May be because of the `[ Projects ]` directory?
Anyways, mystery solved.

**Comment by Enteleform** [comment]
Nice.  That definitely ensures that the current project is renamed.

However, it also closes the project without reopening it automatically.

Is that the intended behavior, or should it be reopening the newly renamed project?

**Comment by randy3k** [comment]
The renamed project should open automatically......unless there is another bug :anguished:

**Comment by Enteleform** [comment]
Looks like there is.

Are there any other places in the code that need `os` paths or separators?

**Comment by randy3k** [comment]
It seems that I know how to reproduce it, do you set `close_windows_when_empty` to true in Sublime settings?

**Comment by randy3k** [comment]
How about the new fix in 0.6.9?

**Comment by Enteleform** [comment]
I use "`close_windows_when_empty": false`

0.6.9 works great, thanks for your help!

**Comment by randy3k** [comment]
Great, it has been a headache for me that some changes only work on some platforms but not the others and I have to switch between platforms to test if a change is good. I should really write some tests for this plugins, though it is a bit difficult as it is GUI related..
