### ISSUE TITLE
[Feature Request] Add Folder

### ISSUE THREAD

**Issue by Enteleform** [randy3k/Project-Manager#48]
There is an __`Add Folder To Project`__ command at `ST-Menu/Projects`.

Please add this feature as __`Project Manager: Add Folder`__ @ the QuickPanel.

The ST command is __`prompt_add_folder`__

**Comment by randy3k** [comment]
There is already a command `Project: Add Folder` in the command palette, why bother to add an equivalent command?

**Comment by Enteleform** [comment]
Gotcha, wasn't aware that there was a default command for this.

Got used to typing `PM` as a prefix for project commands @ the QuickPanel, so it didn't show up with the rest of the Project Manager commands.

**Comment by randy3k** [comment]
Didn't mean to reopen it..
