### ISSUE TITLE
Is there an option to bind "Open Project" without "in New Window"?

### ISSUE THREAD

**Issue by jonnymaceachern** [randy3k/Project-Manager#49]

**Comment by randy3k** [comment]
You could use the default keybind <kbd>cmd+ctrl+p</kbd> (mac) or  <kbd>ctrl+alt+p</kbd> (windows/linux).

If you want to change the default keybind, just use

{
    "keys": ["super+ctrl+o"],
    "command": "project_manager"
}

**Comment by jonnymaceachern** [comment]
Ah, it wasn't previously working because the keybind was in use. Thanks.
