### ISSUE TITLE
Project can't fetch folders

### ISSUE THREAD

**Issue by kumiao** [randy3k/Project-Manager#51]
![image](http://hbimg.b0.upaiyun.com/a0d4d328e2a6c7730dd54b91c0dab870113b8ff125ee0-VARGUb)

**Comment by randy3k** [comment]
Did you ever add any folder to the projects?

**Comment by randy3k** [comment]
Would you check if there are any error messages in the console?

**Comment by kumiao** [comment]
no error messages，if i use project manager open project，project folder should auto displayed in the sidebar，but it not  displayed

**Comment by kumiao** [comment]
I know how it happens，I can not add two project in one of the open sublime text（at once），when i add one project，ctrl+shift+n （open new sublime text）add another ，it works！！! thank you!

**Comment by randy3k** [comment]
Glad that you figured it out.
