### ISSUE TITLE
Update Readme Documentation

### ISSUE THREAD

**Issue by Xtremefaith** [randy3k/Project-Manager#52]
Not sure I fully understand at this moment but correct me if I'm wrong. The current readme says, "It is inspired by Atom's Project Manager" but from looking at that [project link](https://atom.io/packages/project-manager) I do not see any of the features it provides included in this package. Everything I currently see:

* creating new project
* editing project
* renaming project
* etc.

...can already be done in Sublime Text natively. So does this package just provide another menu in the already existing project menu to do the same things differently? If that's the case is that just the starting point and in the end there are more reasonable features to look forward to?

Either way I would update the readme content to reflect a better understanding of what should be expected new capabilities with this package.

Thanks

**Comment by randy3k** [comment]
The first paragraph already indicates the major functionality of this package is to manage `sublime-project` files. It was inspired by Atom's Project Manager because Atom's Project Manager is a "package" for Atom and this is also a "package" of Sublime Text, not the build-in project manager.

**Comment by Xtremefaith** [comment]
Perhaps you can help me better understand what NEW feature it provides in comparison to the "out-of-the-box" feature of Sublime Text. Without your package I can already create and save projects and recall them all through the "Project" menu, so I'm not sure what I'm misunderstanding.

**Comment by randy3k** [comment]
You are right, the built-in project manager creates and saves projects as `sublime-project` files and you have to keep a good record of the locations of the files in order to load the projects. For instance, you can save the `sublime-project` files under the corresponding project root directory, but still, you have to manage the files by yourself.

This package helps by saving all the `sublime-project` files in a centralized location.

**Comment by Xtremefaith** [comment]
I see, I didn't realize that was an issue for people. That makes sense now, I typically already put mine within a centralized location manually.
