### ISSUE TITLE
Cannot use .sublime-project as project directory

### ISSUE THREAD

**Issue by tommaso-petrucciani** [randy3k/Project-Manager#54]
If the project directory is set as "projects_path": ["SOMEPATH/.sublime-project"], then workspace files are created both in that directory and in ".sublime-workspace". Also if using ".sublime-projects", they are created in ".sublime-workspaces".

I think the problem is in pm.py line 268, where the replacement of ".sublime-project" with ".sublime-workspace" is applied to the whole path and not just to the extension.

**Comment by randy3k** [comment]
should be fixed by  0b29413
